### ISSUE TITLE
Stopped receiving Jira notifications

### ISSUE THREAD

**Issue by j-fbriere** [atlassian-labs/atlassian-slack-integration-server#148]
Since the update to the version 2.0.20 of the plugin, Slack stopped receiving notifications from Jira.
The plugin was functioning perfectly well prior to this version.

The plugin is installed on a Jira server version 8.20.1.

I decided to uninstall the plugin and install it again.

Then, when I tried to configure it, on the Applications / Slack page, there was the following error message:

`Unable to reach Slack`
`H2_PRIOR_KNOWLEDGE cannot be used with HTTPS`

So it was impossible to do the configuration.

This is the stack trace of the error found on the Jira server log:
`2021-12-05 17:19:31,187+0000 http-nio-8080-exec-21 url: /rest/slack/latest/connection/can-reach-slack; user: xxxxx WARN xxxxx 1039x830x1 1sx67g xx.xxx.xxx.xx,xxx.xx.x.x /rest/slack/latest/connection/can-reach-slack [c.a.p.slack.util.ResponseMapper] Error when performing request to Slack: api.test
java.net.UnknownServiceException: H2_PRIOR_KNOWLEDGE cannot be used with HTTPS
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.atlassian.plugins.slack.api.client.interceptor.RateLimitRetryInterceptor.intercept(RateLimitRetryInterceptor.java:46)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at com.atlassian.plugins.slack.api.client.interceptor.BackoffRetryInterceptor.intercept(BackoffRetryInterceptor.java:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
        at com.github.seratch.jslack.common.http.SlackHttpClient.postForm(SlackHttpClient.java:45)
        at com.github.seratch.jslack.api.methods.impl.MethodsClientImpl.runPostForm(MethodsClientImpl.java:904)
        at com.github.seratch.jslack.api.methods.impl.MethodsClientImpl.doPostForm(MethodsClientImpl.java:898)
        at com.github.seratch.jslack.api.methods.impl.MethodsClientImpl.apiTest(MethodsClientImpl.java:149)
        at com.atlassian.plugins.slack.api.client.DefaultSlackLimitedClient.lambda$testApi$0(DefaultSlackLimitedClient.java:19)
        at com.atlassian.plugins.slack.util.ResponseMapper.toEither(ResponseMapper.java:23)
        at com.atlassian.plugins.slack.api.client.DefaultSlackLimitedClient.testApi(DefaultSlackLimitedClient.java:19)
        at com.atlassian.plugins.slack.rest.SlackLinkResource.validateSlackReachability(SlackLinkResource.java:163)`

So then I uninstalled the plugin again and decided to manually install the previous version 2.0.18.

Then I was able to configure the plugin.
Now we receive Jira notifications on Slack again.

**Comment by utluiz** [comment]
Thank you for reporting this. We have identified that due to a caching issue version 2.0.20 had an option that forced a different protocol when calling Slack that broken communication.
Version 2.0.21 was released and should fix the problem. Please ignore 2.0.20 and migrate to the newest.

**Comment by procule** [comment]
@utluiz Thanks, I confirm installing 2.0.21 fixed the issue.
We upgraded Jira DC yesterday and began seeing this issue and were worried something went wrong. All will be good for Monday morning :+1:
